image: Visual Studio 2019

build: false
test: false

build_script:
- ps .\build.ps1

deploy:
    provider: GitHub
    github_repo: ZP6400/CS509_HandsOn12
    branch: gh-pages
    auth_token:
        secure: <your-encrypted-github-token>
    on:
        branch: master
